spring:
  application:
    name: Modulo medico
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:postgresql://localhost:8082/FEDERACIONDB
    platform: postgres
    username: postgres
    password: 17893578951
  database:
    driverClassName: org.postgresql.Driver
hibernate:
  hbm2ssl:
    auto: none

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /

javamelody:
  enabled: true
  excluded-datasources: secretSource,topSecretSource
  spring-monitoring-enabled: true
  init-parameters:
    log: true
    monitoring-path: /admin/performance
