server: 
  port: 8085
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://ec2-50-16-197-244.compute-1.amazonaws.com:5432/d40inojiqtoiuj
    platform: postgres
    username: hjnfxwoldhrcec
    password: 933964b90e8c43862e23637427eeb184efd521d563ae79dd5e4d015f2761c9d7
hibernate:
  hbm2ssl:
    auto: none

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /

eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-server-app.herokuapp.com/eureka/

