spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://localhost:8082/FEDERACIONDB
    platform: postgres
    username: postgres
    password: 17893578951
hibernate:
  hbm2ssl:
    auto: none
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /
