server: 
  port: 8085

spring:
  application:
    name: Modulo medico
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:postgresql://ec2-54-221-214-3.compute-1.amazonaws.com:5432/db4v3npp2so16p
    platform: postgres
    username: jjwwxofhujmcrb
    password: 92b4857c8e07c70701eff8127b4a28d63d987786117f7e0eea6e572c3aa79ec2
  database:
    driverClassName: org.postgresql.Driver
hibernate:
  hbm2ssl:
    auto: none

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /

javamelody:
  enabled: true
  excluded-datasources: secretSource,topSecretSource
  spring-monitoring-enabled: true
  init-parameters:
    log: true
    monitoring-path: /admin/performance
