spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://ec2-54-235-114-242.compute-1.amazonaws.com:5432/dcjhubl72upjk6
    platform: postgres
    username: oyudfzxoljlmul
    password: 323ad89baea516a9fa84914c4e1c75f9fd2da68064c8ced2da44b928bf273bea
hibernate:
  hbm2ssl:
    auto: none

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/

