spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://ec2-54-243-47-196.compute-1.amazonaws.com:5432/d3au11fkj3vu3d
    platform: postgres
    username: lwayepuhlbmtwh
    password: 467e8b069ed60229b107000f9517ae4321920da711d483c87c4bc2100868b0c0
hibernate:
  hbm2ssl:
    auto: none

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /

eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-server-app.herokuapp.com/eureka/

